### ISSUE TITLE
parameter not support map[int]int ?

### ISSUE THREAD

**Issue by zhangziang** [PaesslerAG/gval#22]
The following code will panic
```go
	value,err := gval.Evaluate(`a[0] + a[2]`, map[string]interface{}{
		"a":map[int]int{0:1,2:1},
	})
```

**Comment by generikvault** [comment]
fixed it and added your example to the test cases

**Comment by zhangziang** [comment]
@generikvault 
If the map index‘s type is int32 or int64 or float32 …
will get a err.

**Comment by generikvault** [comment]
@zhangziang 
Yes, sorry thats not supported yet. You can  override the VariableSelector in your own project or extend the functionallity in gval via pull request.

**Comment by zhangziang** [comment]
ok, thanks.
Is there some references can help me understand this project？

**Comment by generikvault** [comment]
There's is godoc with an enxample: https://godoc.org/github.com/PaesslerAG/gval#VariableSelector
