### ISSUE TITLE
eval `nil > 1` returns true

### ISSUE THREAD

**Issue by praveen-tt** [PaesslerAG/gval#23]
I am accessing a map or struct fields in expression string, and in case field is not present in map or struct and if compared like Person.Age > 30 then return true.

Reduced issue is "nil > somevalue" return true.

**Comment by generikvault** [comment]
Yeah `nil < 30` is not defined but the lexical order `"nil" < "30"` is and the values are automatically converted into string.
In this case it's really undesirable.

**Comment by generikvault** [comment]
"nil > somevalue" returns an error know
