### ISSUE TITLE
Export parseIf

### ISSUE THREAD

**Issue by mxk** [PaesslerAG/gval#46]
The functions used by the `full` language are not exported, which makes it hard to use them in a custom language. I got around this with `//go:linkname` for now, but was wondering if it might be possible to export them similar to `Parentheses()` and other language components.

**Comment by mxk** [comment]
Ended up re-implementing this function anyway because the original allowed the else clause to be omitted. May be useful to export this and a few other functions anyway, but feel free to close this issue otherwise.

**Comment by generikvault** [comment]
Thank you.

Yeah the current functions implementation is quite rigid. That's the reason why it's not exposed.
