### ISSUE TITLE
Error callback instead of terminating error in JSON

### ISSUE THREAD

**Issue by mariotoffia** [PaesslerAG/gval#55]
Hi and thanks for this greate piece of software! :)

We're using it to do sensor mapping:
* i.e fetch sensor data as a single _HTTP_ request
* map those sensors into our own sensor model. 
 
This works great, except when for some reason we do not get one or more needed sensor data points. In this case it will error out.

Could it be possible to do a callback to an error function instead, and if that error function do return an error, it will fail, otherwise it will remove the json key or set the value to nil (or a value returned by the error function?

```go
func OnError(c context.Context, key, expr string, e error) (val interface{], err error) {}
```

Example mapping document that we use (partial)
```json
{ "tz": TZ,
	"sensors": { 
			"IDT_O3": float64(datapoint["1!6WHH6DKH3CCVW-"].Value),
			"IDT_O5": float64(datapoint["1!6WHH6DKHADPZ1N"].Value), 
                         "AEUPS": float64(datapoint["1!6WHH6DKHICVDSS"].Value * 1000) }
}
```

The error function may act as a `OnErrorResumeNext` or a `circuit-breaker` (the latter is how it currently works).

What do you think about this? Is is hard to implement in your library, would it fit?

To maybe do other than current error handling when [this](https://github.com/PaesslerAG/gval/blob/master/parse.go#L305) or [this](https://github.com/PaesslerAG/gval/blob/master/parse.go#L314) returns an error?

```go
p.Camouflage("object", ',', '}')
key, err := p.ParseExpression(c)
if err != nil {
  return nil, err
}
```

Cheers,
 Mario :)

**Comment by mariotoffia** [comment]
@generikvault does this make sense?

**Comment by generiks** [comment]
Hi Mario,

what you probably wanna do is to use a custom JSON Object interpreter. You can do this with `myLang := gval.Full(PrefixExtension('{', myParseJSONObjectFunction))` in your own lib.

Implement the `myParseJSONObjectFunction` based on the [original](https://github.com/PaesslerAG/gval/blob/3022fab6dfe9e0ff4a5df38d3bfe443f1d053616/parse.go#L260) function with your error handling (line 291) directly in your project.

Cheers,
GeneriK :-)

**Comment by mariotoffia** [comment]
Thanks for your guidande! :)

**Comment by generikvault** [comment]
You're welcome :-)
