### ISSUE TITLE
Unable to accept an array as input to custom function

### ISSUE THREAD

**Issue by timmyimprint** [PaesslerAG/gval#61]
`varsForPassing := map[string]interface{}{
		"AGG311": 1,
		"AGG312": 2,
		"AGG313": 3,
	}

	function := gval.Function("max", func(args ...interface{}) (interface{}, error) {
		arr := args[0].([]float64)
		largest := arr[0]
		for _, val := range arr {
			if val > largest {
				largest = val
			}
		}
		return largest, nil
	})
	value, err := gval.Evaluate("max([AGG311, AGG312, AGG313]) > 1000", varsForPassing, function)
	fmt.Println(value, err)`

I get the error "panic: interface conversion: interface {} is []interface {}, not []float64"

Is it not possible to define an array with variables and use a function on it?

**Comment by generikvault** [comment]
sum is variadic `max(AGG311, AGG312, AGG313) > 1000` works
