### ISSUE TITLE
Error when Not Adding Space for New Operator

### ISSUE THREAD

**Issue by plasticmacaroni** [PaesslerAG/gval#64]
Update - I got things working by adding custom regex to add spaces to my evaluation:

e.g. 4d2 would roll 4 "d2" dice. By adding custom logic to turn 4d2 into "4 d 2" I was able to get things working. Thanks for the support!

**Comment by generikvault** [comment]
hi,
I'm not sure if this can be done. If this is possible than by reconfiguring the Scanner inside the Parser with an Init extension.
Try something like `IsIdentRune = func(ch rune, i int) bool {return unicode.IsDigit(ch)}`
