### ISSUE TITLE
Allow dashes in identfiers

### ISSUE THREAD

**Issue by TomTheBear** [PaesslerAG/gval#83]
I have the case that one of my identifiers contains a `-`, like `type-id`. The parser fails because `-` is not an allowed rune in an identifier.

Example:
```go
func main() {
    vars := map[string]interface{}{"type-id": "4"}
    expr := `type-id == "4"`
    e, err := gval.Full().NewEvaluable(expr)
    if err != nil {
        return
    }
    value, err := e.EvalBool(context.Background(), vars)
    if err != nil {
        return
    }
    fmt.Println(value)
}
```

I could open a PR, but the fix is so simple: Add the condition `(pos > 0 && r == '-')` to https://github.com/PaesslerAG/gval/blob/master/parser.go#L33 . The example works, I tested it even for multiple dashes. But I'm new to gval, so I might miss some cases.

**Comment by hoani** [comment]
I'm a bit late to the party, but it looks like we can do this ourselves now:

```go
  lang := gval.NewLanguage(
    gval.Init(func(ctx context.Context, p *gval.Parser) (gval.Evaluable, error) {
      p.SetIsIdentRuneFunc(func(r rune, pos int) bool {
        return unicode.IsLetter(r) || r == '_' || (pos > 0 && unicode.IsDigit(r)) || (pos > 0 && r == '-')
      })
      return p.ParseExpression(ctx)
    }),
    gval.Full()
  )
```

**Comment by smyrman** [comment]
I suspect this would conflict with the  minus (`-`) operator in the default language. E.g. `a-b` and `a - b` would normally resolve to the same result,  so allowing variable names like `a-b` by default seams like a bad idea.

I didn't try @hoani's work-around, but given there is a work-around, and adding it to the default language seams like a breaking change, perhaps this issue can be considered solved?

**Comment by TomTheBear** [comment]
Yes, thanks. I know the variables names are not good but cannot be changed on my side unfortunately. The workaround works, so I close the issue.
