### ISSUE TITLE
Move `parseIf` operator in `base`

### ISSUE THREAD

**Issue by Dragomir-Ivanov** [PaesslerAG/gval#93]
Greetings,
Kudos for the awesome package!

I do think that `parseIf` operator should be in `base`, because it is useful in `arithmetic`, but is not `arithmetic` operator itself. Currently I am using `.Full()`, instead of just `.Arithmetic()` just because of it.

Best

**Comment by generikvault** [comment]
Hi,

I've exposed `TernaryOperator` so you can mix it yourself with NewLanguage(Arithmetic(), TernaryOperator())

Best

**Comment by Dragomir-Ivanov** [comment]
Thanks a ton!
